use_frameworks!

target 'FFFlowerDemoComponent_Tools_Example' do
  pod 'FFFlowerDemoComponent_Tools', :path => '../'

  target 'FFFlowerDemoComponent_Tools_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
